### ISSUE TITLE
I have multiple Tenants, any future scope of widening the scope on to Azure LightHouse

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#100]
@helderpinto I have multiple Tenants like b2c and want the identities and roles workbooks to be targeting those tenant also, as there are Service Principles residing under those tenants too, where we will be able to see what SPN are expiring under the other tenants, do let us know if we can configure this only for identities and roles.

**Comment by helderpinto** [comment]
Hi, @ashraf2944! AOE was not tested yet in an Azure Lighthouse scenario, but you can address your requirements by leveraging an undocumented feature, You'll notice that every Export-* runbook has a couple of parameters that are never used in a regular setup:

- `externalTenantId` - GUID of the external Azure AD tenant
- `externalCredentialName` - name of the Azure Automation Credential object you create with the Application ID and secret of an SPN with Global Reader privileges on the external tenant.
- `externalCloudEnvironment` - name of the Azure cloud, e.g., `AzureCloud` for Azure Global, `AzureChinaCloud` for Azure China and `AzureUSGovernment` for the Azure US Gov cloud.

For each of the external tenants you want to bring into AOE, you must
1. create an Automation schedule, for example `AzureAutomation_ExportAADTenantXDaily`, with a daily recurrence at the time you wish.
1. create an Automation credential for the SPN you created and assigned Global Reader access to the external tenant, using the SPN Application ID as the credential user name and the SPN secret as the password.
1. link the `Export-AADObjectsToBlobStorage` and the `Export-RBACAssignmentsToBlobStorage` runbooks to the schedule created above and configure the runbook parameters with the external tenant ID, credential name you created in the previous step and, if needed, the external cloud environment name.

**Comment by ashrafcitius** [comment]
@helderpinto Do you have an example of this? I am just trying to understand what would be the cintent of the automation script and how to link with the Export-AADObjectsToBlobStorage and the Export-RBACAssignmentsToBlobStorage, that would be of great help.

**Comment by ashraf2944** [comment]
@helderpinto I was able to complete all step, just confused on the 3rd step which you mentioned "and configure the runbook parameters with the external tenant ID, credential name you created in the previous step and, if needed, the external cloud environment name."  where should i configure the parameter for external Tenant?

**Comment by helderpinto** [comment]
@ashraf2944 and @ashrafcitius, for both runbooks, first, click on the "Link to schedule" button:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/9320fd47-1327-4dff-8be1-7a8f81f47f45)

Then, link it to the schedule you created in step 1:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/ca6a97f7-9e61-466b-940a-41f3d20ea6b6)

Then, finally, configure the parameters:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/23c6350e-aab3-4da4-adad-8aa9befe6e7b)

**Comment by ashrafcitius** [comment]
@helderpinto Thank you so much!! This really mean alot.

**Comment by ashraf2944** [comment]
@helderpinto I did all the things that you informed me above, but i cant see anything on the dashboard also i did selected the Tenant and both the Tenant are showing the same name, below is the screenshot of the error, on the permission level i created a SPN and assigned it Global Reader rights on to the Tenant but still no Output.

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/bd50209e-5ec8-4146-9531-f42649e6bcff)

**Comment by helderpinto** [comment]
Hi @ashraf2944! The error you are getting and the absence of Azure AD objects (the queries return no results for the top two Azure AD counts) means that probably the `Export-AADObjectsToBlobStorage` runbook did not run successfully for that specific tenant. Please, check the output of that job.

**Comment by ashraf2944** [comment]
@helderpinto I have not received any error, i can see the Output in the runbook but i do see a warning displaying below:

"The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant."

**Comment by helderpinto** [comment]
Please, check that the credential you passed as a parameter for the `Export-AADObjectsToBlobStorage` runbook refers to a Service Principal that exists in the external tenant. Interestingly, it seems the `Export-RBACAssignmentsToBlobStorage` runbook ran successfully for the same external tenant. Can you compare both and check whether the credential and other parameters are the same?
