### ISSUE TITLE
Remove SQL Database if no need of PowerBI

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#101]
Hello @helderpinto just wanted to know if we dont need Power Bi report can we remove SQL Database or is their any dependence of SQL Database with the other runbooks which we can see on Workbook?

**Comment by helderpinto** [comment]
The SQL Database holds other data besides recommendations. It is used to store suppressions (if any) and, more importantly, as a control registry for ingest jobs. You must keep the database for the correct operation of the engine.
