### ISSUE TITLE
Impact of removing SQL Database from the workflow

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#102]
@helderpinto Just wanted to know if we dont need Power Bi report, is it finr if we remove SQL Database and also wanted to know what are the dependencies on the runbook that we can remove, because i am very much fine with the workbook and dont need PowerBi

**Comment by helderpinto** [comment]
@ashraf2944 , this was answered before. See #101 .

**Comment by ashraf2944** [comment]
@helderpinto I had one more question, any reason we are not using Azure Table Storage instead of SQL Database.

**Comment by helderpinto** [comment]
@ashraf2944, Azure Table Storage was indeed used in the early days of AOE, but as the solution evolved, moving to Azure SQL made it easier to maintain and to integrate with Power BI and other external visualization tools. But if AOE were to be rebuilt from scratch, SQL would maybe be replaced by a lighter approach. May I know how the SQL Database is impacting you?
