### ISSUE TITLE
api still correct for the billing reader role on the EA accounts for the MI?

### ISSUE THREAD

**Issue by cpen-blm** [helderpinto/AzureOptimizationEngine#104]
| The Enterprise Enrollment Reader role could 
     | not be verified. Status Code: 404;
     | Response: {"code":"NotFound","message":"The 
     | resource or one of its dependencies could   
     | not be found."}

Is the api version still correct? I get this trying to run the PS for the EA Reader roles granting to the system managed identity
Do I need to add any secrets or anything to that MI first? or possible api version issue?

Thanks

**Comment by helderpinto** [comment]
@cpen-blm, I confirm the API is still working as expected. Are you sure the Billing Account ID you specified is correct? Open the [Cost Management + Billing](https://portal.azure.com/#view/Microsoft_Azure_GTM/ModernBillingMenuBlade/~/Overview) blade in the Azure Portal and then open the "Properties" menu option. You'll find there the correct Billing Account ID value 

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/6f57e285-a6d8-4ec4-9f54-91662aa2527d)

**Comment by cpen-blm** [comment]
We do get our EA from a reseller so playing around in the portal with the developer tools I did have to change the api version and the body being sent to the following to get it to work in our environment:
            $uri = "https://management.azure.com/providers/Microsoft.Billing/billingAccounts/$billingAccountId/billingRoleAssignments/$($billingRoleAssignmentName)?api-version=2020-12-15-privatepreview"
            $body ="{`"id`":`"redacted`",`"type`":`"armResource`",`"name`":`"PutBillingRoleAssignmentByBillingAccountAsync`",`"properties`":{`"principalId`":`"$principalId`",`"principalTenantId`":`"$tenantId`",`"userAuthenticationType`":`"Organization`",`"roleDefinitionId`":`"24f8edb6-1668-4659-b5e2-40bb5f3a7d7e`"}}"

Also it looks like https://management.azure.com is changing to  https://consumption.azure.com per this doc: https://learn.microsoft.com/en-us/azure/cost-management-billing/automate/migrate-ea-reporting-arm-apis-overview

Will this toll get updated or do we need to migrate to that new api ourselves? 

Thank you

**Comment by helderpinto** [comment]
Hi, @cpen-blm. I am glad you managed to work around the limitations of your EA. Regarding the API changes, it's the other way around: `consumption.azure.com` (which by the way as never used by AOE) is being deprecated and customers are advised to use instead `management.azure.com` (Azure Resource Manager REST API), which AOE actually does.

**Comment by cpen-blm** [comment]
ah gotcha - thanks for the explanation.
