### ISSUE TITLE
SQL Database Server Use case in AOE

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#105]
@helderpinto Just want to understand below things over here:

1) The workflow of SQL Database server in AOE Architecture if you can help me understand how the data is ingested into SQL Database server and where does the output of the SQL Database server go and which workbook is being used to do that.

2) I need to understand what if we only want the Recommendation workbook and remove the other, in this case what needs to be done.

Any help would be really appreciated!!

**Comment by helderpinto** [comment]
@ashraf2944, this topic should preferably be opened in the [Discussions](https://github.com/helderpinto/AzureOptimizationEngine/discussions) area, as this is not an issue per se. Answering your questions:

1. The SQL Database has 4 tables, being 2 of them (`LogAnalyticsIngestControl` and `SqlServerIngestControl`) used to control the latest raw data export file that was processed per resource type. There's also a table (`Filters`) that can be used by customers to dismiss recommendations that do not apply to their environments, by using a PowerShell tool. Finally, there's the `Recommendations` table that is used by the Power BI report and also by the `Remediate-*` runbooks (off by default). As you can see, none of these tables are used by any Workbook, but some of them are critical to the whole functioning of AOE.
2. Given my answer above, there are no Workbooks directly depending on the SQL Database. Therefore, I guess there aren't Workbooks you want to remove.

Please, let me know if this answers your queries.

**Comment by ashraf2944** [comment]
@helderpinto We were actually working on saving our cost on the automation account runbook, thats the reason we were thinking to only consider recommendation workbook and runbook specifically related to it and exclude the remaining workbook.

is there anything we can do for that?

**Comment by helderpinto** [comment]
Most of the Automation Account runbooks are required by the Recommendations workbook. Are there workbooks besides the Recommendations one for which you see less value and would accept discarding? For your reference, these workbooks are independent from the Recommendations one:
- Reservations Usage
- Reservations Potential
- Policy Compliance
- Identities and Roles
- Benefits Usage
- Benefits Simulation

An other thing you can do is identifying custom recommendations that are less relevant for you, so that you disable the runbooks that contribute to them. Let me know which recommendations you value the most and which one you can discard.

**Comment by ashraf2944** [comment]
@helderpinto I was thinking of playing with the schedules and to change the schedules, so the schedules which are hourly i will schedule it to daily and the schedules which are daily will schedule it for every 2 days and the weekly ones to schedule it for 2 weeks, this way i think we will be able to reduce our cost on the automation account, as automation account cost is dependent on the number of hours the runbook is running, let me know your thoughts on it also if you see any issues please can you let us know what would be the impact?

**Comment by helderpinto** [comment]
I advise you to start simple, by just adjusting the hourly schedules, which are the ones with a greater impact on your Azure Automation bill. These schedules are all associated with the `Export-AzMonitorMetricsToBlobStorage` runbook. If you change those schedules to, let's say, a 6-hour frequency, you must also unlink and re-link the runbook respectively to each schedule and change the `TimeSpan` parameter to `06:00:00` (see example below). You must ensure the job parameters are consistent with the schedule frequency. 

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/f9ac28f7-b309-4144-a24c-77c6402a5ee4)

Changing the frequency of the other schedules (daily and weekly) will not have a significant impact on your bill and will require much more complicated, not recommended changes in AOE.

Anyways, I am intrigued about your desire to lower the Azure Automation costs. How big are they? And how large is your environment (how many VM Scale Sets, Disks, SQL Databases, and App Service Plans)? Can you share this information?

**Comment by ashraf2944** [comment]
@helderpinto We have pretty large environment and that is one of the reason why i am trying to reduce the tool cost as much as possible below is our resource count:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/3bf544c5-7fe6-426c-a166-270ac9853ec6)

**Comment by helderpinto** [comment]
@ashraf2944, definitely, with such a high number of App Service Plans and Managed Disks, the `Export-AzMonitorMetricsToBlobStorage` jobs are probably consuming most of your Azure Automation bill. I recommend you follow the steps I described above, namely:

1. Change the `AzureOptimization_ExportMonitor*Hourly` schedules frequency from 1 hour to whatever you want (up to 12 hours).
1. Take note of the parameters associated to each `Export-AzMonitorMetricsToBlobStorage` runbook job schedule (the `TimeSpan` parameter will be the only one you'll need to change). The parameter value to copy is what is inside double quotes. For example, where you see `"Average"`, you should copy `Average` only.
1. Unlink the schedule from the runbook (see example below)
1. Re-add the schedule to the runbook, putting in the parameters you copied from step 2, except `TimeSpan`, which you are going to change to a value consistent with the hourly frequency you chose in step 1. For example, if you chose a 6-hour frequency, the value should be `06:00:00`.

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/9438b894-d021-4329-bd62-e7f42f9cf6c4)

**Comment by ashraf2944** [comment]
@helderpinto Thank you so much for this!! I will definitely try this out and will let you know, meanwhile i was just having a confusion on why there is no cost involved if the SQL database is ingesting data into Log analytics workspace?

**Comment by helderpinto** [comment]
@ashraf2944, I did not get your point. There are always costs for the SQL Database, though small. If you don't need recommendations to be ingested in the SQL Database, you can always turn the `Ingest-RecommendationsToSQLServer` runbook off, to keep the database size stable. However, the database is always needed for other purposes. You cannot disable it.

**Comment by ashraf2944** [comment]
@helderpinto I am talikng about the custom tables that are getting creating in Log analytics workspace.

basically if we are nit having AMA agent deployed deployed on our VM's then on what basis wil Log analytics consume cost?

**Comment by helderpinto** [comment]
All `Export-*ToBlobStorage` runbooks together with the `Ingest-OptimizationCSVExportsToLogAnalytics` runbook populate the Log Analytics workspace with `AzureOptimization_*` logs spread across multiple tables. These tables are needed to generate recommendations which are in turn stored in a different Log Analytics table (and in the SQL database, if you want to keep the SQL ingestion runbook on). Please review the architecture [here](https://github.com/helderpinto/AzureOptimizationEngine?tab=readme-ov-file#architecture).
