### ISSUE TITLE
Deploy AOE in predefined resource group

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#109]
@helderpinto  We are having a resource group with the contributor access on it, just wanted to know what changes need to be made in azuredeploy.json so that it takes the same resource grouo instead of creating new one.

**Comment by helderpinto** [comment]
@ashraf2944, there is no need to change the deployment template. When running the deployment script, you have the option to choose a resource group and resource naming of your choice. You just have to avoid entering a name prefix, by typing ENTER when asked for it. See example below: 

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/00a54b00-07f7-43d8-957c-b905b43d7521)
