### ISSUE TITLE
Gettimg recommendation runbook error

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#111]
Hello @helderpinto I am getting below error for all recommendation runbooks:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/e09484a1-a394-4e85-a443-934c7ffbe317)

Because of this the recommendation dashboard is not generating data:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/0997189c-070c-4151-aabf-e217c13a4681)

Any help would be greatly appreciated!

**Comment by helderpinto** [comment]
@ashraf2944, can you please run the query below in the Log Analytics workspace used by the AOE and share the results?

``` kql
union AzureOptimization*
| where TimeGenerated > ago(7d)
| summarize count() by Type
| order by Type
```

**Comment by ashraf2944** [comment]
@helderpinto Below is the result of the query:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/103f6874-0426-40ea-b531-34af9a59603a)
![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/92ae8299-1dc3-418c-9c83-30953c36bbc2)

**Comment by helderpinto** [comment]
Apparently, you have all the logs needed to generate recommendations. You even have 3319 entries in the `
AzureOptimizationRecommendationsV1_CL` table, which should be enough to populate the Recommendations workbook. There is a table missing - `AzureOptimizationPricesheetV1_CL`, impacting some of the recommendations - but you should still be getting other recommendations that do not depend on it.

For each of the failing `Recommend-` runbook, there's a Warning log entry starting as follows: "Query failed. Debug the following query in the AOE Log Analytics workspace: ". Can you copy the query that follows this message and try to run it in the AOE workspace, and see what error is presented? Please, do this for 2 or 3 different runbooks and share the errors here. 

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/10661605/550182ec-37ed-4f36-9b84-0506f7fc350e)

**Comment by ashraf2944** [comment]
The error automatic got resolved!! Thank You so much for your help!!
