### ISSUE TITLE
EA account addition throws code 400

### ISSUE THREAD

**Issue by attilabus16092020** [helderpinto/AzureOptimizationEngine#116]
Error description: 
When choosing EA account the request body is not correct therefore we receive error 400.
Exception:
The Enterprise Enrollment Reader role could not be granted. Status Code: 400; Response: {"errors":{"Properties.PrincipalId":["PrincipalId or UserEmailAddress/UserAuthenticationType must be
     | specified."],"Properties.RoleDefinitionId":["The RoleDefinitionId field is required."],"Properties.UserEmailAddress":["PrincipalId or UserEmailAddress/UserAuthenticationType must be
     | specified."],"Properties.UserAuthenticationType":["PrincipalId or UserEmailAddress/UserAuthenticationType must be specified."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One
     | or more validation errors occurred.","status":400,"traceId":"<traceID>"}

In the code the URI body does not contain properties object
MS article: https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/assign-roles-azure-service-principals

Code snippet:
   `                 $body = "{`"principalId`":`"$principalId`",`"principalTenantId`":`"$tenantId`",`"roleDefinitionId`":`"/providers/Microsoft.Billing/billingAccounts/$billingAccountId/billingRoleDefinitions/24f8edb6-1668-4659-b5e2-40bb5f3a7d7e`"}"`

To be code:
`                    $body = "{`"properties`": {`"principalId`":`"$principalId`",`"principalTenantId`":`"$tenantId`",`"roleDefinitionId`":`"/providers/Microsoft.Billing/billingAccounts/$billingAccountId/billingRoleDefinitions/24f8edb6-1668-4659-b5e2-40bb5f3a7d7e`"}}"`

**Comment by helderpinto** [comment]
Hi, @attilabus16092020 . Thank you for reporting this issue. It seems you are indeed correct. Can you confirm you have successfully granted the needed role with the code fix you suggested? Can you also check whether the fix proposed [here](https://github.com/helderpinto/AzureOptimizationEngine/compare/master...dev-issue116) will solve the issue?

**Comment by attilabus16092020** [comment]
HI @helderpinto,

It does. :)
