### ISSUE TITLE
Runbook jobs getting suspended

### ISSUE THREAD

**Issue by ashraf2944** [helderpinto/AzureOptimizationEngine#118]
@helderpinto All of my runbook jobs are getting suspended and i am getting below error in my Output of job for every runbook, also just to inform you i already have a Hybrid workder group for this which is running fine.

{"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '1/30/2024 10:23:59 AM' is earlier than current UTC time '1/30/2024 11:00:46 AM'."}}

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/40d1d6c3-1584-4c1b-a8cf-31d4bb5ca61c)

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/2b8fab20-7295-404b-894f-f21e8fafa0b4)

**Comment by helderpinto** [comment]
@ashraf2944, the problem you are describing is not specific to AOE. It seems your Hybrid Worker machines' system time is out of sync. Please, open an Azure support ticket if the problem persists.

**Comment by ashraf2944** [comment]
@helderpinto I was ale to resolve it and now i am getting following issues for all the recommendation runbooks excluding AAD/Advisor:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/47142914/10b2cb85-6d91-4548-afcf-acd3826f9485)

**Comment by helderpinto** [comment]
It seems you somehow broke AOE by removing a variable it needs. Please follow the instructions provided by the error message. The variable value should a date in the yyyy-MM-dd format.

**Comment by rasselmaliyekkal** [comment]
> @helderpinto I was ale to resolve it and now i am getting following issues for all the recommendation runbooks excluding AAD/Advisor:
> 
> ![image](https://private-user-images.githubusercontent.com/47142914/301168713-10b2cb85-6d91-4548-afcf-acd3826f9485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTAxMDMsIm5iZiI6MTcwNzgwOTgwMywicGF0aCI6Ii80NzE0MjkxNC8zMDExNjg3MTMtMTBiMmNiODUtNmQ5MS00NTQ4LWFmY2YtYWNkMzgyNmY5NDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA3MzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4Mjk0ODk4ZTU1YTg3MmEyYWY2NGM0OTAxYmJhNmY5YmMyZGIyODJlMmMwMTY5ZDI1Y2UxYzQ5YWVlNzcyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h18vx2fVxcO_vYxxiB4ExYUz7mvhOyy-Nb0AYyduO3I)

Can you help, how you resolve job suspend issue.??

**Comment by rasselmaliyekkal** [comment]
@ashraf2944 - Can you please tell, how you fixed job suspend issue.??
