### ISSUE TITLE
Not all subscriptions are listed

### ISSUE THREAD

**Issue by lkshck** [helderpinto/AzureOptimizationEngine#123]
Hey, I deployed the engine into my dedicated FinOps subscription and data is imported, but in the workbooks it only shows data from this subscription and not all the other ones we have in the tenant. The only thing missing currently is the global reader role for the managed identity. Is this required to get data for all subscriptions? As I'm currently not that interested in those Entra things, I thought it could work without this role, as my User has at least the Enterprise Agreement Administrator role which should provide the billing data for the whole tenant.
Best regards,
Lukas

**Comment by helderpinto** [comment]
Hi, Lukas. To make the most of AOE, you need to manually grant the Azure `Reader` role at a higher scope than the subscription where AOE was deployed in. See more details [here](https://github.com/helderpinto/AzureOptimizationEngine?tab=readme-ov-file#widening-the-scope-of-aoe-recommendations---more-subscriptions-or-more-workspaces).

You don't need to grant `Global Reader` in Entra ID if you're not interested in the Identities and Roles Workbook and recommendations.

**Comment by lkshck** [comment]
Ah, didn’t saw it. Thanks for the hint. Assigned the role and will now wait for the data to show up.
