### ISSUE TITLE
Not able to view any tables in the SQL Database and unable to assign the roles. 

### ISSUE THREAD

**Issue by cutekoti** [helderpinto/AzureOptimizationEngine#133]
Hi, 
I am trying to deploy the Azure Optimization Engine downloaded from the repository with the following settings. However, the deployment is failing with the error: **Tenant ID, application ID, principal ID, and scope are not allowed to be updated**, as shown below.

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/2690402/3d5fafbf-1da9-4112-85ad-70d3e30a645e)

Could someone help with this please?

**Comment by helderpinto** [comment]
Hi @cutekoti. It seems you are trying to redeploy AOE after a deployment you deleted before. There is an orphan Reader role assignment at the subscription scope (which belonged to a previous AOE deployment) that you are trying to overwrite with this new deployment, which is not permitted. Please, remove first the orphan Reader role assignment (it should be easy to spot, as it has an "Identity not found" name). After that, the new deployment should succeed.

**Comment by cutekoti** [comment]
> Hi @cutekoti. It seems you are trying to redeploy AOE after a deployment you deleted before. There is an orphan Reader role assignment at the subscription scope (which belonged to a previous AOE deployment) that you are trying to overwrite with this new deployment, which is not permitted. Please, remove first the orphan Reader role assignment (it should be easy to spot, as it has an "Identity not found" name). After that, the new deployment should succeed.

Thanks @helderpinto. I was able to deploy with the following errors after removing the existing reader role assignments. How can I fix the Billing Profile reader role issue? 
![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/2690402/6822c4c6-3d45-4df9-aa64-4dad2f21126e)

**Comment by helderpinto** [comment]
@cutekoti , you must be a Billing Profile Owner (on the MCA Billing Profile you targeted the deployment against) to be able to grant the Billing Profile Reader role to AOE. Anyways, AOE will start generating recommendations today. The lack of the Billing Profile Reader role does not impact the ability to generate recommendations. It impacts some Workbooks, though. If you want to fixe that, ensure you have the required permissions and run the [Setup-BenefitsUsageDependencies.ps1](https://github.com/helderpinto/AzureOptimizationEngine/blob/master/Setup-BenefitsUsageDependencies.ps1) script.

**Comment by cutekoti** [comment]
That Worked. Thank you - @helderpinto

**Comment by cutekoti** [comment]
Thanks all for your help.
