### ISSUE TITLE
Replace Az Advisor right-size target SKUs with customer-defined SKU families

### ISSUE THREAD

**Issue by helderpinto** [helderpinto/AzureOptimizationEngine#14]
Let's say Az Advisor recommends downsizing to a SKU a customer does not want to use for whatever reason (Reservations policy, performance requirements, etc.). AOE should allow customers to provide a list of allowed SKU families, from which Az Advisor recommendations would be updated to use a SKU from those families instead.

**Comment by helderpinto** [comment]
@sriniambati, I guess this is what you suggested.

**Comment by sriniambati** [comment]
@helderpinto, yes. You have captured the requirement correctly.

**Comment by helderpinto** [comment]
Added to the backlog.
