### ISSUE TITLE
Get-AzConsumptionPriceSheet

### ISSUE THREAD

**Issue by justinharty1** [helderpinto/AzureOptimizationEngine#39]
Hello again, 

Utilizing azure us government, with Get-AzConsumptionPriceSheet in Recommend-AdvisorCostAugmentedToBlobStorage

noticed that get-azconsumptionpricesheet returns:
Get-AzConsumptionPriceSheet: Operation returned an invalid status code 'NotFound'

Id          :
Name        :
PriceSheets : {}
Tag         :
Type        :

hmnm, ran it with -debug
got a snippit 

"error": {
    "code": "404",
    "message": "Cost management data is not supported for subscription(s) xxx in the provided api-version. Please use api-version 2019-10-01 or later. (Request ID: yyy)"

going to do more research on rights to subscription cost management and azure us government

Update: https://github.com/MicrosoftDocs/azure-docs/issues/38660
Changing the API version to the previous stable release (2019-01-01) allows the filter to work.
This is an example of the full URI: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Consumption/usageDetails?api-version=2019-05-01&$filter=properties/resourceGroup eq 'dev-rg'

where the -debug of the command reported using
Absolute Uri:
https://management.usgovcloudapi.net/subscriptions/xxx/providers/Microsoft.Consumption
/pricesheets/default?$top=1000&api-version=2018-01-31

**Comment by justinharty1** [comment]
hmm, can't seem to find a way (not powershell command guru) to change the URL for this command to update to a newer or the specified api version...

**Comment by helderpinto** [comment]
Unfortunately, the API version is hardcoded in the PowerShell module and cannot be changed from outside. We'll have to wait for the module to update to latest API version. A work-around can be to abandon the Az.Billing PowerShell module/wrapper and implement the REST conversation directly with the API. However, not accessing the Pricesheet shouldn't break the runbook. You should see a "Consumption pricesheet not available, will estimate savings based in cores count..." log and the runbook would proceed normally. Can you confirm?

**Comment by justinharty1** [comment]
yes, it continues on, with the estimation.
