### ISSUE TITLE
Cost Growing Workbook not showing any data

### ISSUE THREAD

**Issue by Tapan1684** [helderpinto/AzureOptimizationEngine#44]
Costs Growing workbook is not showing any data. Below error is getting. Any suggesstion

Evolution over time (select growing/outlier cost)
This query could not run because some parameters are not set.
Please set: SelectedPerspective, SelectedPerspectiveId

Top contributing instances over time
This query could not run because some parameters are not set.
Please set: SelectedPerspective, SelectedPerspectiveId

Top contributing resource groups over time
This query could not run because some parameters are not set.
Please set: SelectedPerspective, SelectedPerspectiveId
![cost_growing1](https://user-images.githubusercontent.com/82101639/123527146-25641600-d6ab-11eb-898f-7f71375dc800.JPG)

**Comment by helderpinto** [comment]
Thank you for reporting this. Queries 2-4 depend on the top left query. If no growing/outlier costs were found, then the other queries will show the "query could not run" message. Try to adjust time range to an interval larger than 1w and also adjust min. daily cost and growth % to values that are closer to your environment. If the main query still shows no results. then your environment has not exhibited cost anomalies for the selected time range.
