### ISSUE TITLE
Work Analytics Workspace workbooks?

### ISSUE THREAD

**Issue by justinharty1** [helderpinto/AzureOptimizationEngine#45]
looking over the workbooks in the log analytics workspace, two work, but a third doesn't appear to ..
Is this something I need to set and haven't seen in the documentation because I am silly?

This query could not run because some parameters are not set.
Please set: SelectedPerspective, SelectedPerspectiveId

![image](https://user-images.githubusercontent.com/79268264/124126568-cdc9ff80-da48-11eb-8c24-ebf340f259ff.png)

**Comment by helderpinto** [comment]
Actually, the documentation needs to be improved. You're not the first one reporting this (duplicate of #44). Please let me know if the answer in the duplicate issue helps. Thanks!

**Comment by justinharty1** [comment]
Thanks for the update.  This then is about time and waiting for the data to build, and such I imagine.  I have less than 30 days of data built up from the scheduling, I will just have to wait at this point, but I know the time frame issue at this point.
