### ISSUE TITLE
Power BI File Date Filter Issue

### ISSUE THREAD

**Issue by justinharty1** [helderpinto/AzureOptimizationEngine#46]
On the 7th Day of a recommendation cycle, prior to the weekly Recommendation runs, the Power BI View filters out the Week Old Data, and does not have new data to replace it with...

This Test Installation within a subscription has a first run on 6/22, second run on 6/29, and todays run has yet to occur
I have verified all the current recommendation data is in the power BI file
![image](https://user-images.githubusercontent.com/79268264/124615497-5549b100-de43-11eb-96bb-fbf4217d282b.png)
![image](https://user-images.githubusercontent.com/79268264/124615855-9e016a00-de43-11eb-998d-17cf5547f607.png)

Note: I know that I can change the schedule to go after hours or before I start using the views etc, but this introduces a window of time your view will not work if you setup the wrong scheduling.

**Comment by helderpinto** [comment]
Thank you for reporting this. Yes, the date filter must be improved to keep the latest recommendations always available. This will be addressed in the next release.

**Comment by helderpinto** [comment]
With the newest version, which includes an Azure Workbook to visualize recommendations, no further investments will be made in the Power BI dashboard.
