### ISSUE TITLE
Deployment failing for microsoft.operationalinsights/workspace

### ISSUE THREAD

**Issue by kumara79** [helderpinto/AzureOptimizationEngine#49]
"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"ResourceDeploymentFailure","message":"Encountered internal server error. Diagnostic information: timestamp '20220111T025224Z', subscription id 'a5197234-610b-4f87-8f44-a8665e7e8a9d', tracking id '16690699-2899-45e3-9bb0-2b5e2e9bbcd6', request correlation id '0c2d7113-c7a3-4d05-b2aa-e6565501cf3c'."},{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'http://amsweb.amsweb/subscriptions/a5197234-610b-4f87-8f44-a8665e7e8a9d/resourcegroups/arg-syd-platform-mgmt-management/providers/microsoft.operationalinsights/workspaces/law-syd-platform-mgmt-01' does not support the API version '2021-12-01-preview'."}]}

**Comment by helderpinto** [comment]
@kumara79, I was not able to reproduce this issue. Can you please provide details about your deployment? Did you use Azure Cloud Shell? Which inputs did you provide to the deployment questions? I see your resource URI starts with http://amsweb.amsweb. Are you trying to deploy this in Azure Stack? The AOE is fully supported only in Azure Commercial and Azure US Gov.

**Comment by kumara79** [comment]
@***@***.***>

I have deployed it multiple times since morning by changing the API versions as well and no success so far. I have used Powershell ISE, VScode powershell 7 terminal and Cloudshell and everytime I deploy, I get this error message

Status Message: The HTTP resource that matches the request URI
'http://amsweb.amsweb/subscriptions/213a43e6-d89c-4310-bbce-638fd4420fdf/resourcegroups/rg-guardian/providers/microsoft.operationalinsights/workspaces/law-guard-001' does not support the
API version '2021-12-01-preview'. (Code:UnsupportedApiVersion)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code:
DeploymentFailed)
- {
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI
'http://amsweb.amsweb/subscriptions/213a43e6-d89c-4310-bbce-638fd4420fdf/resourcegroups/rg-guardian/providers/microsoft.operationalinsights/workspaces/law-guard-001' does not support the
API version '2021-12-01-preview'.",
    "innerError": null
  }
} (Code:BadRequest)
CorrelationId: 2bc1276d-1e98-4d02-a694-cfba3707a5df
At C:\Temp\AOE-Jan2022\Deploy-AzureOptimizationEngine.ps1:488 char:27
+ ... eployment = New-AzDeployment -TemplateUri $TemplateUri -Location $tar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureSubscriptionDeploymentCmdlet


The message points to API version '2021-12-01-preview' which seems to be hardcoded somewhere. I search the whole code and couldn’t able to find this api version.

The below are the inputs I provided using create a new log analytics workspace.

PS C:\Temp\AOE-Jan2022> .\Deploy-AzureOptimizationEngine.ps1
@{WorkspaceResourceGroupName=ak-rg-guard200; NamePrefix=EmptyNamePrefix; StorageAccountName=stocorguardian001; SqlServerName=pid-cor-sql-01; AutomationAccountName=pid-cor-aaa-guardian01; Reso
urceGroupName=pid-cor-rg-guardian01; SubscriptionId=213a43e6-d89c-4310-bbce-638fd4420fdf; TargetLocation=australiasoutheast; WorkspaceReuse=y; SqlDatabaseName=guardiandb; WorkspaceName=law-gu
ard-200; SqlAdmin=sqladmin}
Found last deployment options above. Do you want to repeat/upgrade last deployment (Y/N)?: n
Getting Azure subscriptions (filtering out unsupported ones)...
[0] Landing Zone 2
[1] Landing Zone 1
[2] Platform
[3] Landing Zone 2
---
Please, select the target subscription for this deployment [0..3]: 1
Please, enter a unique name prefix for the deployment or existing prefix if updating deployment (if you want instead to individually name all resources, just press ENTER):
Are you going to reuse an existing Log Analytics workspace (Y/N)?: n
Please, enter the new or existing Resource Group for this deployment: rg-guardian
Enter the Storage Account name: stoguardian001
Automation Account name: aa-guard-001
Azure SQL Server name: sql-guard-001
Azure SQL Database name: guard_db
Log Analytics Workspace: law-guard-001
Checking name prefix availability...
...for the Storage Account...
...for the Log Analytics workspace...
...for the Azure SQL Server...
Chosen resource names are available for all services
Getting Azure locations...
[0] australiacentral
[1] australiaeast
[2] australiasoutheast
[3] brazilsouth
[4] canadacentral
[5] canadaeast
[6] centralindia
[7] centralus
[8] eastasia
[9] eastus
[10] eastus2
[11] francecentral
[12] germanywestcentral
[13] japaneast
[14] japanwest
[15] koreacentral
[16] northcentralus
[17] northeurope
[18] norwayeast
[19] southafricanorth
[20] southcentralus
[21] southeastasia
[22] southindia
[23] swedencentral
[24] switzerlandnorth
[25] uaenorth
[26] uksouth
[27] ukwest
[28] westcentralus
[29] westeurope
[30] westus
[31] westus2
[32] westus3
---
Please, select the target location for this deployment [0..32]: 1
Please, input the SQL Admin username: sqladmin
Deploying Azure Optimization Engine to subscription Landing Zone 1. Continue (Y/N)?: y
Automation schedules base time automatically set to 2022-01-11 07:58:14Z.
Deploying Azure Optimization Engine resources...
New-AzDeployment : 4:10:04 PM - The deployment 'rg-guardian220111155521' failed with error(s). Showing 2 out of 2 error(s).
Status Message: The HTTP resource that matches the request URI
'http://amsweb.amsweb/subscriptions/213a43e6-d89c-4310-bbce-638fd4420fdf/resourcegroups/rg-guardian/providers/microsoft.operationalinsights/workspaces/law-guard-001' does not support the
API version '2021-12-01-preview'. (Code:UnsupportedApiVersion)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code:
DeploymentFailed)
- {
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI
'http://amsweb.amsweb/subscriptions/213a43e6-d89c-4310-bbce-638fd4420fdf/resourcegroups/rg-guardian/providers/microsoft.operationalinsights/workspaces/law-guard-001' does not support the
API version '2021-12-01-preview'.",
    "innerError": null
  }
} (Code:BadRequest)
CorrelationId: 2bc1276d-1e98-4d02-a694-cfba3707a5df
At C:\Temp\AOE-Jan2022\Deploy-AzureOptimizationEngine.ps1:488 char:27
+ ... eployment = New-AzDeployment -TemplateUri $TemplateUri -Location $tar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureSubscriptionDeploymentCmdlet


I tried deploy both using the existing log analytics and creating a new one and each time I get this error message. I am deploying in Australia East region.

Regards

Amit.

**Comment by helderpinto** [comment]
Thanks for reporting this, @kumara79. Although still not able to reproduce, I have a guess for the root cause. I made some changes to the ARM template. Can you please try to deploy using this command:

`./Deploy-AzureOptimizationEngine.ps1 -TemplateUri "https://raw.githubusercontent.com/helderpinto/AzureOptimizationEngine/issue49fix/azuredeploy.json"`

**Comment by kumara79** [comment]
@***@***.***> I have deployed using the below uri and it is working.

What have you changed? What should I be looking if I get this error again?

And above all Thank you very much for your prompt support around this. Much appreciated! 😊

Regards
Amit.

**Comment by helderpinto** [comment]
I am glad it worked, @kumara79! You can see what I changed [here](https://github.com/helderpinto/AzureOptimizationEngine/commit/56ec20356b847199006d7357f93a7176793edae2). Basically, I was dynamically getting the API version for the OperationalInsights provider, which, for your Azure context, was returning an unsupported API version. I fixed the API version according to the remainder of the template, which makes the template more consistent after all. Many thanks for your feedback!

**Comment by sivasun01** [comment]
I am getting the same error when deployment 

Deploying Azure Optimization Engine resources...
New-AzDeployment: /home/system/azureoptimizationengine/Deploy-AzureOptimizationEngine.ps1:488
Line |
 488 |  … eployment = New-AzDeployment -TemplateUri $TemplateUri -Location $tar …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 7:19:41 PM - Error: Code=InternalServerError; Message=Encountered internal server error. Diagnostic information: timestamp
     | '20220401T191941Z', subscription id 'cab23135-a220-4637-bdf3-0656f5588d8c', tracking id '5c617284-9201-4cc1-bb19-915df87a79d3', request
     | correlation id '5c617284-9201-4cc1-bb19-915df87a79d3'.

The Json file to fix the issue is not avaliable now

**Comment by helderpinto** [comment]
@sivasun01, the JSON file that fixed the issue was meanwhile merged into the `master` branch. The error you are getting is different. Have tried to deploy again, with the same options. Sometimes, the deploy fails due to conflicts in the Automation Modules deployment. Otherwise, please look at the Deployments details in the Resource Group you chose for the AOE.
