### ISSUE TITLE
not having recommendations from all subscriptions

### ISSUE THREAD

**Issue by albandrod** [helderpinto/AzureOptimizationEngine#52]
I have implemented the AOE for one Azure tenant which has multiple subscriptions, and all the VMs are reporting to a single LogAnalytics Workspace. I already have set up permission for the Managed Identity at Management group scope, but when I'm trying to execute queries against the recommendations, I only receive recommendations from the subscriptions where I installed the AOE.

What I'm doing wrong?

**Comment by helderpinto** [comment]
What do you mean when you say you "execute queries against the recommendations"? Are you manually triggering the Automation runbooks? Are you running KQL queries in Log Analytics or in Azure Resource Graph?

If you assigned the Reader role to the Automation Account Managed Identity at the Management Group scope - and this scope covers multiple subscriptions - then you should simply let the Automation runbook do their job at the scheduled times and you will eventually see the recommendations for all those subscriptions come out.

**Comment by albandrod** [comment]
Hi, you're reight, after giving the permission to the MI, and give the AO some time to process all the new information, I'm able to see the information from the different sub in the PowerBI and also in the LA workbooks. 

My mistake was to fire the different KQL queries without giving the AO to do his job. After waiting some time, everything works like a charm.

Thanks!
