### ISSUE TITLE
LogAnalytics Custom Tables are not created

### ISSUE THREAD

**Issue by mmaroth-BRONGA** [helderpinto/AzureOptimizationEngine#54]
Hi, We have deployed this solution as per the documentation and added multiple Log analytics workspaces for VM/VMSS perf metrics. Runbooks are running as per schedulers, but when we check workspace for these custom tables, we dont see them and workbooks are throwing table not found errors.

AzureOptimizationVMsV1_CL
AzureOptimizationResourceContainersV1_CL
AzureOptimizationConsumptionV1_CL
AzureOptimizationAdvisorV1_CL

As result of which, recommendations exporter runbook throwing tables not found (0 records found) message.

**Comment by helderpinto** [comment]
@mmaroth-BRONGA, I understand other tables are being populated correctly and only these 4 ones have no data. Can you please check if the following runbooks have been running correctly, I mean have they completed successfully and do their logs indicate data rows were generated?

- Export-ARGVirtualMachinesPropertiesToBlobStorage
- Export-ARGResourceContainersPropertiesToBlobStorage
- Export-ConsumptionToBlobStorage
- Export-AdvisorRecommendationsToBlobStorage

Furthermore, the Ingest-OptimizationCSVExportsToLogAnalytics runbook executions should have evidence of having ingested into Log Analytics the rows coming from the CSVs exported by the runbooks above, which should have been stored in the following Storage containers:

- argvmexports
- argrescontainersexports
- consumptionexports
- advisorexports

**Comment by slamho** [comment]
Hi there, I am having a similar issue. 

i get these errors when i go into the **Workbooks**:
'where' operator: Failed to resolve table or column expression named 'AzureOptimizationVMsV1_CL'...
'where' operator: Failed to resolve table or column expression named

I am new to this and not sure how to resolve. Please can you give me a detailed steps of how to fix it.  

regards,

**Comment by helderpinto** [comment]
@slamho, please review my previous comment to original issue posted by @mmaroth-BRONGA . Also, you must give a couple of hours to AOE, so that it has time to export data, ingest it into Log Analytics and have it indexed by the Log Analytics service. It may take 2 to 3 hours after deployment.

**Comment by slamho** [comment]
@helderpinto. thanks for the response!

The solution was deployed last week Thursday.

 When i look at the above-mentioned runbooks I can see they all completed successfully. I checked the output and see they all ran ok with **DONE** at the end. In the output i can also see it exporting to the CSV file or uploading to CSV to Storage.

When i go to the AOE's storage account, and scroll to Storage browser, it shows me there is data in the Blob containers and Tables (Only system generated tables exist).

I'm assuming these Tables should have been created in the storage account as part of the deployment?  
AzureOptimizationVMsV1_CL
AzureOptimizationResourceContainersV1_CL
AzureOptimizationConsumptionV1_CL
AzureOptimizationAdvisorV1_CL

**I think i found out why they weren't created.**

When I try to manually add the table, it gives an error with the name not conforming. When i remove the underscore, it accepts it.  

![AOE - Azure table error](https://user-images.githubusercontent.com/107250475/173060911-090a760f-b8a1-44cb-ac2a-37467f19d8b2.png)

![AOE - Azure table correct naming std](https://user-images.githubusercontent.com/107250475/173061244-eb3a752e-fbc7-45d6-81c3-df00883b9261.png)

![AOE - No tables](https://user-images.githubusercontent.com/107250475/173063487-5461193f-e677-49ce-9083-5ce9b4d34086.png)

**Comment by helderpinto** [comment]
@slamho, AOE does not use Storage Tables. It uses Log Analytics tables. You should open the Log Analytics workspace created/reused as part of the AOE deployment and look for Custom Logs.

![image](https://user-images.githubusercontent.com/10661605/173078862-dd11a3f1-ae90-423f-8224-2317368f1700.png)

Don't forget to check the `Ingest-OptimizationCSVExportsToLogAnalytics` runbook, as I referred to in a [comment above](https://github.com/helderpinto/AzureOptimizationEngine/issues/54#issuecomment-1152183598).

**Comment by helderpinto** [comment]
@slamho, the only custom log that is being ingested is the AzureOptimizationMonitorMetricsV1_CL. This means that either:

1. The Export-* runbooks are not generating CSVs in other Storage Containers (`argvmexports`, `argrescontainersexports`, `consumptionexports`, `avisorexports`, etc.)
2. The `Ingest-OptimizationCSVExportsToLogAnalytics` runbook does not have the required schedules to process those Storage containers. 

If you can't find the reason for these issues, can you try deploying AOE again, using the same options you chose in the initial deployment? The deployment script will just update the setup, fixing missing/incomplete resources and keep existing data untouched.

**Comment by slamho** [comment]
@helderpinto Thanks for the feedback. I manually ran the Remediate runbook and it seems to have created the CL tables now. I also noticed the Remediate runbooks have no schedules.

![CL Tables](https://user-images.githubusercontent.com/107250475/173405505-79f2b3b1-e931-41ab-a23a-d12c4b7b31df.png)

I am going to leave it and let all schedules run for the week. Will check it on Friday and let you know.

**PS: My PowerBI report is blank. Do i need to transform data for it to display?**

**Comment by helderpinto** [comment]
@slamho, remediation runbooks do not create any table. The only runbook that is capable of doing it is `Ingest-OptimizationCSVExportsToLogAnalytics`. But I am glad you were finally able to see some data flowing in the Log Analytics workspace.

After setting up the Power BI report according to the [instructions](https://github.com/helderpinto/AzureOptimizationEngine#visualizing-recommendations-with-power-bi), you must wait for the first successful execution of the `Ingest-RecommendationsToSQLServer` runbook and then refresh the Power BI report. That runbook will collect all the generated recommendations and insert them into the SQL Database where the recommendations history is stored.

**Comment by helderpinto** [comment]
Remediation runbooks should be scheduled ONLY if you want to automatically fix recommendations. For example, resizing a VM according to recommended size or deleting an unattached disk. Azure customers generally like to have control over when and how they remediate recommendations, especially in production environments. However, it may be a perfectly valid approach to automatically remediate resources in dev/test environments. As this feature is undocumented, please review carefully the runbook code to understand what is done and in which conditions.

The Transform Data step in the Power BI setup is not required, unless you want to customize some of the report columns with your own tags.

**Comment by helderpinto** [comment]
@mmaroth-BRONGA , `AdvisorCostAugmentedToBlobStorage` will generate results only if Azure Advisor is currently providing Cost recommendations for the subscriptions in the scope of AOE. Having 0 results is not unusual if Azure Advisor considers your environment fully cost optimized (see [full list of potential Cost recommendations](https://docs.microsoft.com/en-us/azure/advisor/advisor-reference-cost-recommendations)). However, you also have the custom Cost recommendations that were developed specifically for AOE (VMs deallocated for a long time, unattached disks, Public IPs, etc.).

**Comment by mmaroth-BRONGA** [comment]
Thank you @helderpinto  Now we are able to see recommendations in PowerBI.
