### ISSUE TITLE
No Right-Size data being populated

### ISSUE THREAD

**Issue by jplattvirtuellegroup** [helderpinto/AzureOptimizationEngine#57]
Hi All,

Hoping somebody can assist me with this. I am having trouble with no information coming through for the VM right sizing (page shows blank) and in general there are less recommendations than expected. Additionally, the Azure Advisor right-sizing recommendations are not present here either (not sure if that is by design or not).  I changed the date range to be 1 month and also refreshed many times over a period of 2 weeks

From what I can see, all the subscriptions appear to be visible to the AOE, because I can see some recommendations for each subscription (i.e. Subnets without any IP usage are a waste of virtual network address space)

During the setup, I noticed our customer already had some VMs attached to log analytics workspaces, I can confirm that I added the AzureOptimization_RightSizeAdditionalPerfWorkspaces variable to the automation account and added all of the workspaces to this 2 weeks ago.

Also, I ensured that the Automation App account has reader access to the tenant root group which has reader access to all subscriptions and log workspaces.

Additional Info;
- I am using the provided PowerBI sample report 
- I Have run the "./Setup-LogAnalyticsWorkspaces.ps1 -AutoFix" for all workspaces
- There are 10 subscriptions in total, all of which are PAYG
- The AOE has been running for 3 weeks as of time of writing (15-09-2022)

**Comment by helderpinto** [comment]
@jplattvirtuellegroup, thank you for raising the issue and for sharing the details. Advisor recommendations are included in AOE, together with the custom recommendations. What you describe may be a consequence of one of the export jobs failing to collect data from Advisor. Can you please have a look at the latest job from the `Export-AdvisorRecommendationsToBlobStorage` runbook and share the log output here?

Another possible cause is the `Recommend-AdvisorCostAugmentedToBlobStorage` runbook not generating any recommendations. Again, if you can share the log output, that'll be helpful.

If you find any job failing in the last week, please share also its logs and exception.

Finally, can you please explain what you mean by 

> (...) I changed the date range to be 1 month (...)
?

Have you changed any schedule or Automation variable? Change these variables carefully, as some depend on others and may break AOE if not managed carefully.

**Comment by jplattvirtuellegroup** [comment]
Thanks for the prompt reply @***@***.***>

Firstly, confirming that the date range was just the filter within the powerBI sample report, not any variables or schedules.

Confirming that you are correct, the Recommend-AdvisorCostAugmentedToBlobStorage runbook is failing. There is a warning from the last run, it appears perhaps it is not running against all subscriptions;  "TenantId 'xxxxx' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext."

Full Output Log;

Logging in to Azure with ManagedIdentity...

Environments
------------
{[AzureChinaCloud, AzureChinaCloud], [AzureCloud, AzureCloud], [AzureGermanCloud, AzureGermanCloud], [AzureUSGovernme...


Name               : Internal IT (xxxx) - xxxx-
                     xxxx
Account            : xxxx
Environment        : AzureCloud
Subscription       : xxxx
Tenant             : xxxx
TokenCache         :
VersionProfile     :
ExtendedProperties : {}

Getting subscriptions target


Name               : Internal IT (xxxx) - xxxx-
                     xxxx
Account            : xxxx
Environment        : AzureCloud
Subscription       : xxxx
Tenant             : xxxx
TokenCache         :
VersionProfile     :
ExtendedProperties : {}

Found 3 raw recommendations. Filtering out suppressed ones...

Continuing processing 3 recommendations...

Found 3 recommendations (all) for xxxx subscription

Exported to JSON: 3 lines

JSON Import: 3 lines

Export to 20220915-all-xxxx.csv


ICloudBlob                         : Microsoft.Azure.Storage.Blob.CloudBlockBlob
BlobType                           : BlockBlob
Length                             : 1851
IsDeleted                          : False
BlobClient                         : Azure.Storage.Blobs.BlobClient
BlobBaseClient                     : Azure.Storage.Blobs.Specialized.BlockBlobClient
BlobProperties                     : Azure.Storage.Blobs.Models.BlobProperties
RemainingDaysBeforePermanentDelete :
ContentType                        : text/csv
LastModified                       : 9/15/2022 1:55:09 AM +00:00
SnapshotTime                       :
ContinuationToken                  :
VersionId                          :
IsLatestVersion                    :
AccessTier                         : Cool
TagCount                           : 0
Tags                               :
Context                            : Microsoft.WindowsAzure.Commands.Storage.AzureStorageContext
Name                               : 20220915-all-xxxx.csv

[2022-09-15T01:55:09.385Z] Uploaded 20220915-all-xxxx.csv to Blob Storage...

[2022-09-15T01:55:09.479Z] Removed 20220915-all-xxxx.csv from local disk...

[2022-09-15T01:55:09.573Z] Removed 20220915-all-xxxx.json from local disk...


Name               : Access to Azure Active Directory (xxxx) -
                     xxxx- xxxx
Account            : xxxx
Environment        : AzureCloud
Subscription       : xxxx
Tenant             : xxxx
TokenCache         :
VersionProfile     :
ExtendedProperties : {}

----

Confirming also, that there are a lot of failed jobs, most I checked appear to have the warning that there is more than one subscription, and also "Upcoming breaking changes in the cmdlet 'Get-AzPolicyAssignment' :"

Let me know if you need the full output of the below

Recommend-VMSSOptimizationsToBlobStorage
9/15/2022, 1:10:00 PM
Failed
Azure
9/15/2022, 1:12:09 PM
Recommend-VMsHighAvailabilityToBlobStorage
9/15/2022, 1:10:00 PM
Failed
Azure
9/15/2022, 1:10:27 PM
Recommend-UnusedLoadBalancersToBlobStorage
9/15/2022, 1:10:00 PM
Failed
Azure
9/15/2022, 1:10:27 PM
Recommend-UnusedAppGWsToBlobStorage
9/15/2022, 1:10:00 PM
Failed
Azure
9/15/2022, 1:10:26 PM
Recommend-SqlDbOptimizationsToBlobStorage
9/15/2022, 1:10:00 PM
Failed
Azure
9/15/2022, 1:10:26 PM
Export-AdvisorRecommendationsToBlobStorage
9/15/2022, 11:55:00 AM
Failed
Azure
9/15/2022, 11:55:10 AM
Export-PolicyComplianceToBlobStorage
9/15/2022, 11:40:00 AM
Failed
Azure
9/15/2022, 11:40:53 AM
Export-PolicyComplianceToBlobStorage
9/14/2022, 11:40:00 AM
Failed
Azure
9/14/2022, 11:40:37 AM
Export-PolicyComplianceToBlobStorage
9/13/2022, 11:40:00 AM
Failed
Azure
9/13/2022, 11:40:45 AM
Export-PolicyComplianceToBlobStorage
9/12/2022, 11:40:00 AM
Failed
Azure
9/12/2022, 11:40:45 AM
Export-PolicyComplianceToBlobStorage
9/11/2022, 11:40:00 AM
Failed
Azure
9/11/2022, 11:40:44 AM
Export-AzMonitorMetricsToBlobStorage
9/11/2022, 3:55:00 AM
Failed
Azure
9/11/2022, 3:55:30 AM
Export-PolicyComplianceToBlobStorage
9/10/2022, 11:40:00 AM
Failed
Azure
9/10/2022, 11:40:35 AM
Export-PolicyComplianceToBlobStorage
9/9/2022, 11:40:00 AM
Failed
Azure
9/9/2022, 11:40:45 AM
Recommend-VMSSOptimizationsToBlobStorage
9/8/2022, 1:10:00 PM
Failed
Azure
9/8/2022, 1:11:54 PM
Recommend-SqlDbOptimizationsToBlobStorage
9/8/2022, 1:10:00 PM
Failed
Azure
9/8/2022, 1:10:28 PM
Recommend-VMsHighAvailabilityToBlobStorage
9/8/2022, 1:10:00 PM
Failed
Azure
9/8/2022, 1:10:28 PM
Recommend-UnusedAppGWsToBlobStorage
9/8/2022, 1:10:00 PM
Failed
Azure
9/8/2022, 1:10:22 PM
Recommend-UnusedLoadBalancersToBlobStorage
9/8/2022, 1:10:00 PM
Failed
Azure
9/8/2022, 1:10:11 PM
Export-AzMonitorMetricsToBlobStorage
9/8/2022, 11:55:00 AM
Failed
Azure
9/8/2022, 11:55:21 AM
Export-AdvisorRecommendationsToBlobStorage
9/8/2022, 11:55:00 AM
Failed
Azure
9/8/2022, 11:55:16 AM
Export-PolicyComplianceToBlobStorage
9/8/2022, 11:40:00 AM
Failed
Azure
9/8/2022, 11:40:46 AM
Ingest-OptimizationCSVExportsToLogAnalytics
9/7/2022, 12:10:00 PM
Failed
Azure
9/7/2022, 12:10:28 PM
Export-PolicyComplianceToBlobStorage
9/7/2022, 11:40:00 AM
Failed
Azure
9/7/2022, 11:40:46 AM
Export-PolicyComplianceToBlobStorage
9/6/2022, 11:40:00 AM
Failed
Azure
9/6/2022, 11:40:41 AM

**Comment by helderpinto** [comment]
@jplattvirtuellegroup, the output you shared is coming from `Export-AdvisorRecommendationsToBlobStorage`, not from `Recommend-AdvisorCostAugmentedToBlobStorage`. I guess I found the reason: the job is failing after iterating over an "Access to Azure Active Directory" subscription. This type of subscription is a legacy one that does not support the ARM REST API. I've commited a potential fix for this issue. Can you please, replace the code of the `Export-AdvisorRecommendationsToBlobStorage` runbook with the one available [here](https://github.com/helderpinto/AzureOptimizationEngine/blob/v1.9/runbooks/data-collection/Export-AdvisorRecommendationsToBlobStorage.ps1) and let me know if the job now runs successfully?

**Comment by jplattvirtuellegroup** [comment]
Thanks for the update @***@***.***> that is now running successfully! 😊

Assume other runbooks will need the same update? Or is there a way I can exclude these subscriptions?


Kind Regards,

Jay Platt | Senior Systems Engineer
Virtuelle Group | Level 10, 1 Rider Boulevard, Rhodes NSW 2138
Phone: +61 2  8090 3626 Option 2
https://virtuellegroup.com.au
Sydney  |  Melbourne  |  Auckland  |  Singapore  |  China
***@***.***<https://virtuellegroup.com.au/cybersecurity>

This message contains confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message you must not view, disseminate, copy or take any action in reliance on it. If you have received this message in error please notify Virtuelle Group Pty Ltd immediately. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the views of Virtuelle Group Pty Ltd.

**Comment by helderpinto** [comment]
Thanks for the feedback, @jplattvirtuellegroup! You are correct. You'll need to replace the code of the following runbooks (the link points to the fixed version):

- [Export-PolicyComplianceToBlobStorage](https://github.com/helderpinto/AzureOptimizationEngine/blob/v1.9/runbooks/data-collection/Export-PolicyComplianceToBlobStorage.ps1)
- [Export-RBACAssignmentsToBlobStorage](https://github.com/helderpinto/AzureOptimizationEngine/blob/v1.9/runbooks/data-collection/Export-RBACAssignmentsToBlobStorage.ps1)

The other failures you reported are not related with this issue. If the other problems persist, please open a new issue.
