### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by guidovbrakel** [helderpinto/AzureOptimizationEngine#62]
I really like the concept of this, but I would like to deploy this at resource group level and not at subscription scope.. I have been looking around but can't seem to change it, is there anyone from team who can assist?

**Comment by helderpinto** [comment]
Hi @guidovbrakel, what do you mean by resource group level deployment? Having the solution generating recommendations only for a specific resource group? Or do you have something else in mind?

**Comment by helderpinto** [comment]
Closing due to lack of feedback.
