### ISSUE TITLE
Support for CSP subscriptions

### ISSUE THREAD

**Issue by spike28742** [helderpinto/AzureOptimizationEngine#70]
### Discussed in https://github.com/helderpinto/AzureOptimizationEngine/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **spike28742** March 22, 2023</sup>
Hi 

When I try to deploy I am getting an error that the subscription is not supported.  I managed to deploy the solution about a month ago.  Are there any limitations why the solution will not work on a CSP based subscription?  

Also noticed that the cost recommendations never worked, are there any specific requirements for these to work?

Thanks for your support and keep up the great work on this tool.</div>

**Comment by helderpinto** [comment]
Thank you for raising this issue, @spike28742. It was recently addressed in the conversation around pull request #67. You'll find there the answers to your questions. Based on the feedback, the AOE recently got a new deployment switch (`AllowUnsupportedSubscriptions`) that allows customers using CSP and other unsupported subscriptions to still use the tool at their own risk. See the [FAQ](https://github.com/helderpinto/AzureOptimizationEngine#frequently-asked-questions) for more details.

**Comment by lukemurraynz** [comment]
Note": I will add a note to my blog article to reference the FAQ.
