### ISSUE TITLE
Request to add VM Resizing Recommendation instead of Augmenting Advisor

### ISSUE THREAD

**Issue by rasselmaliyekkal** [helderpinto/AzureOptimizationEngine#75]
Azure Advisor not giving VM resizing Recommendations as per the docs, we have created few VMs with size Standard D4as v5 (4 vcpus, 16 GiB memory), which was running without any application ( max CPU utilisation < 6%). Still after 3 weeks no advisor recommendation.

As per the doc https://learn.microsoft.com/en-in/azure/advisor/advisor-cost-recommendations#resize-sku-recommendations , we should get the recommendation.

Can you kindly include VM resizing recommendation as well, instead of augmenting advisor.

**Comment by helderpinto** [comment]
Thanks for raising this issue @rasselmaliyekkal. 

Providing its own algorithm for VM resizing recommendations is in the AOE roadmap, but there is no ETA at the moment. It requires a significant effort to develop and maintain and it would not bring an outstanding value, considering Azure Advisor's own right-size algorithm is effective enough. 

Regarding your problem, I recommend you first check the [Advisor low usage threshold](https://learn.microsoft.com/en-us/azure/advisor/advisor-get-started#configure-low-usage-vm-recommendation) (default is 5%)? If the problem persists, open an Azure Support ticket to understand why Advisor is not recommending right-sizing your VMs.
