### ISSUE TITLE
TLS version too old  for storage

### ISSUE THREAD

**Issue by cpen-blm** [helderpinto/AzureOptimizationEngine#77]
Could you please update the storage like you did the SQL for the later TLS version?

**Comment by helderpinto** [comment]
Thank you for reporting this, @cpen-blm. This will be fixed in the next version release (see [commit](https://github.com/helderpinto/AzureOptimizationEngine/commit/226e9cf0df0abad8a45973913cbc3d1c38a17d4a)). The `allowBlobPublicAccess` property will also be set to `false` along the way.
