### ISSUE TITLE
Automation Account Hybrid worker issue

### ISSUE THREAD

**Issue by arunjvai** [helderpinto/AzureOptimizationEngine#80]
The Jobs from the Runbook Ingest-RecommendationsToSQLServer  show the below error:

>The runbook job failed due to a job stream being larger than 1MB, the limit that is supported by an Azure Automation sandbox. See some common ways to resolve this at https://aka.ms/AAjobstreamlimit

I then use the Hybrid worker option as you have provided in the documentation. The hybrid worker is an Azure VM using the OS - Windows Server 2022 Datacenter Azure Edition

```
.\Reset-AutomationSchedules.ps1
.\Deploy-AzureOptimizationEngine.ps1 -DoPartialUpgrade
```

Installed all the latest modules for Azure Powershell on the worker VM and now I get the below exception while I run the jobs for the runbook.

> Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.PowerShell.Clients.ResourceManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=xxxx' does not have an implementation. 

There has been numerous posts on how to fix it like the ones below, but I have not been able to fix it.

https://learn.microsoft.com/en-us/answers/questions/1299863/how-to-fix-method-get-serializationsettings-does-n

https://github.com/Azure/azure-powershell/issues/21647

Is there any proper guidance on how to use the right steps to use the hybrid worker for using the AOE solution ?

**Comment by arunjvai** [comment]
The Runbook  Job Export-AzMonitorMetricsToBlobStorage  also fails due to the above mentioned Exception.

**Comment by helderpinto** [comment]
@arunjvai , based on the links you shared, it seems the issue you are reporting is related to a conflict between a recent version of the `Az.Accounts` module and other modules. The current version of the Azure Optimization Engine was tested against previous module versions. You can find the list of required modules and their specific versions [here](https://github.com/helderpinto/AzureOptimizationEngine/blob/master/upgrade-manifest.json). Please, uninstall the Az PowerShell module from your system and install only the required modules referring to the specific versions AOE was tested against. You can install a specific module version using a command like the one below:

```powershell
Install-Module -Name Az.Accounts -RequiredVersion 2.10.4
```

**Comment by arunjvai** [comment]
The runbooks are now running fine except for a few due to other reasons. This worked as suggested by making sure only the specfic versions of the modules were being set 
![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/124654835/b4a8bce8-491a-406a-8b2a-fa98daa7478e)

**Comment by arunjvai** [comment]
This can be closed based on my previous update. Thanks for the support !
