### ISSUE TITLE
Multiple Subscriptions not being loaded in the Database

### ISSUE THREAD

**Issue by arunjvai** [helderpinto/AzureOptimizationEngine#82]
The recommendations table currently only shows the Subscription name of the  Subscriptions where the AOE solution resides, as shown below 

<img width="121" alt="image" src="https://github.com/helderpinto/AzureOptimizationEngine/assets/124654835/e78a3cab-633d-48e7-bc56-2cc2a996e155">

We have more than 10 Subscriptions, so how can this data get populated? 

I am not sure if this is related to an earlier issue that I have reported #80

**Comment by helderpinto** [comment]
Please refer to the [article in the documentation](https://github.com/helderpinto/AzureOptimizationEngine#widening-the-scope-of-aoe-recommendations---more-subscriptions-or-more-workspaces) dedicated to your issue.

**Comment by arunjvai** [comment]
This was already done., but still shows the same in the DB. Please advise where I need to look further to find the root cause.

**Comment by helderpinto** [comment]
@arunjvai , can you please run the following query in the AOE Log Analytics workspace? It should return all your subscriptions and their respective names, provided you assigned the Reader role to the AOE MU in those subscriptions or in a management group containing them.

```kql
AzureOptimizationResourceContainersV1_CL
| where TimeGenerated > ago(2d)
| where ContainerType_s =~ 'microsoft.resources/subscriptions' 
| summarize arg_max(TimeGenerated, *) by SubscriptionGuid_g
| project SubscriptionGuid_g, SubscriptionName = ContainerName_s 
```

**Comment by arunjvai** [comment]
Yes, the query that you provided returns the Subscription GUID and name successfully.

I have already given the AA system level Managed Identity Reader at the Root Management Group, this has been applied also to the VM's Managed Identity Role. Can you please expand on the  Abbreviation MU that you were referring to?

**Comment by helderpinto** [comment]
The MU abbreviation was a typo. I meant MI (Managed Identity). It seems you have all the conditions for the subscription name to populate in the database. Bear in mind that some recommendations do not have an associated subscription. This is the case of Azure AD service principal credentials recommendations, for example. But, for the vast majority of recommendations, the subscription name should be there. Can you do the following additional checks?

- In the `recommendationsexports` container of the AOE storage account, open one of the `advisor-asis-*.json` blobs and check whether all entries have a `SubscriptionName` property correctly filled.
- In the AOE Log Analytics workspace, run the query below. It should return all the subscription names that have been generating recommendations.

```kql
AzureOptimizationRecommendationsV1_CL
| where TimeGenerated > ago(8d) and isnotempty(SubscriptionName_s)
| distinct SubscriptionName_s
```

- Open the `Recommendations` Workbook available in the AOE Log Analytics workspace. You should find there all the subscriptions in the Subscriptions filter.

If you're still seeing a single subscription name in all the 3 tests, than it means there's only one subscription generating recommendations. All the others have no conditions for recommendations at the moment.

**Comment by arunjvai** [comment]
So, I can see the Subscription names in the  advisor-asis-*.json blobs and I can also see the subscription names while running the Kusto query in the mentioned LAW. The Recommendations Workbook also lists the Subscriptions in the Subscriptions Filter.

Just checked the Recommendations Table in the DB again and I still see the NULL values under the Subscription Column.

**Comment by arunjvai** [comment]
I am waiting for the schedule to run tomorrow for the job Ingest-RecommendationsToSQLServer, and see the result as it has been failing till now due to various issues. But as you had mentioned, I was able to see only two entries by running the query you had mentioned.
1. Subscription name where the AOE solution has been installed.
2. Null value 

If the NULL value signifies the tenant level recommendations then what is the process to enable this at each subscription level ? Or do I need to wait for this job to run and check this again ?

**Comment by helderpinto** [comment]
The tenant-level recommendations are generated by the `Recommend-AADExpiringCredentialsToBlobStorage` runbook. All the other `Recommend-*` generate subscription-level recommendations,. The `Ingest-RecommendationsToSQLServer` runbook ingests all those recommendations into the SQL Database. Let's wait for this job to run successfully and, hopefully, you'll see all the subscriptions in the Power BI report.

**Comment by helderpinto** [comment]
@arunjvai, did the recommendations database eventually got populated with additional subscriptions? Can we close this issue?

**Comment by arunjvai** [comment]
> 

Yes, it has been reflected.
