### ISSUE TITLE
Status Message: Management Policy is not valid. Error details: Could not find member 'tags' on object of type 'ManagementPolicyJune19'.

### ISSUE THREAD

**Issue by ashrafcitius** [helderpinto/AzureOptimizationEngine#90]
i was able to succesfully apply the tags and resources are getting deployed except runbooks and  now i am getting error, below error, any idea?

New-AzDeployment : 4:00:14 PM - The deployment 'azureoptengncloudcoe-rg230904155820' failed with error(s). Showing 3 out of 47 error(s).
Status Message: Management Policy is not valid. Error details: Could not find member 'tags' on object of type 'ManagementPolicyJune19'. Path 'tags', line 1, position 8. For more information, see - https://aka.ms/managementpolicies (Code:InvalidManagementPolicy)
Status Message: Validation errors while reading content link. (Code:BadRequest)
Status Message: Validation errors while reading content link. (Code:BadRequest)

**Comment by ashrafcitius** [comment]
Below is the error that i am getting for Runbook deployment, is that because o have added tags to runbook and ingest block too?

{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Validation errors while reading content link."
    }
}

**Comment by helderpinto** [comment]
@ashrafcitius, I understand you edited the `azuredeploy.json`. Azure Automation runbooks do support tagging, as you can see [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts/runbook). 

As I don't have visibility over the ARM template you were trying to deploy, I am not able to help you. Please, share the template for further diagnosis.

**Comment by ashrafcitius** [comment]
[azuredeploy.txt](https://github.com/helderpinto/AzureOptimizationEngine/files/12514115/azuredeploy.txt)

**Comment by ashrafcitius** [comment]
@helderpinto PFA file.

**Comment by helderpinto** [comment]
These resource types do not support tags or do not require tags, because they're sub-resources:

```
Microsoft.Storage/storageAccounts/blobServices
Microsoft.Storage/storageAccounts/blobServices/containers
Microsoft.Storage/storageAccounts/managementPolicies
Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies
Microsoft.Automation/automationAccounts/variables
Microsoft.Automation/automationAccounts/credentials
Microsoft.Automation/automationAccounts/schedules
Microsoft.Automation/automationAccounts/jobSchedules
```

**Comment by ashrafcitius** [comment]
This is the error now i am getting for runbook, removed the tags which you mentioned above:

Status Message: Validation errors while reading content link. (Code:BadRequest)
Status Message: Validation errors while reading content link. (Code:BadRequest)
Status Message: Validation errors while reading content link. (Code:BadRequest)

**Comment by helderpinto** [comment]
@ashrafcitius, a new release of AOE has been released and you are able now to deploy it specifying resource tags. For example:

```powershell
$tags = @{"Service"="aoe";"Environment"="Demo"}
.\Deploy-AzureOptimizationEngine.ps1 -ResourceTags $tags
```

Please, upgrade your project to the latest version.
