### ISSUE TITLE
While deploying Runbook {"code":"BadRequest","message":"Validation errors while reading content link."}

### ISSUE THREAD

**Issue by ashrafcitius** [helderpinto/AzureOptimizationEngine#92]
Hello Hlder,

I am stuck at runbook where its giving me error: {"code":"BadRequest","message":"Validation errors while reading content link."}

because of which the jobschedules is also getting failed as its saying cannot find runbook.

**Comment by helderpinto** [comment]
@ashrafcitius, have you updated to the latest version of AOE? You shouldn't be using your custom ARM template anymore. Just follow the installation instructions with the `-ResourceTags` parameter.

**Comment by ashrafcitius** [comment]
Yes @helderpinto  I did used it but its giving me below error.

C:\temp\AzureOptimizationEngine-master\AzureOptimizationEngine-master\Deploy-AzureOptimizationEngine.ps1 : Cannot bind argument to parameter 'Path' because it is an empty string.
At line:1 char:1
+ .\Deploy-AzureOptimizationEngine.ps1 -ResourceTags $tags
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Deploy-AzureOptimizationEngine.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Deploy-AzureOptimizationEngine.ps1

**Comment by helderpinto** [comment]
Thanks for reporting this, @ashrafcitius, and for sharing the details. There was a bug with the deployment script in PowerShell 5.1. It has been fixed. Please download the latest version and let me know out it goes.

**Comment by ashrafcitius** [comment]
@helderpinto Thank you so much for this, its finally working woohoo!! Really appreciate your help its great!!
