### ISSUE TITLE
Currency change from EUR to USD

### ISSUE THREAD

**Issue by ashrafcitius** [helderpinto/AzureOptimizationEngine#93]
@helderpinto while changing the currency from EUR to USD under Recommendation Workbook> Cost, if i change it from EUR to USD from portal itself the cost doesnt change it shows the same EUR currency cost, may i know how we can change it to USD to reflect the exact cost, does that needs to be done from code or from portal, and if code then where should i make the changes to reflect the exact cost in USD.

**Comment by helderpinto** [comment]
@ashrafcitius, thank you for the question. According to the AOE FAQs:

**Q: What is the currency used for costs and savings?** 
A: The currency used is the one that is reported by default by the Azure Consumption APIs. It should match the one you usually see in Azure Cost Management.

Every cost/saving value in AOE uses the currency of your consumption agreement. The Recommendations Workbook allows you to select a currency code, but it does not impact the actual values. It is there only for you to choose the currency code shown in headers and charts, to make the report more readable, in case you share it with others in your organization.

Maybe the Workbook should have a note about this fact. I'll add it in the next release. If you have further comments, they're welcome.

**Comment by ashrafcitius** [comment]
@helderpinto  our consumption agreement is in USD, but still its showing EUR weird.

**Comment by helderpinto** [comment]
@ashrafcitius , your consumption agreement is in USD and the values you're seeing across all AOE workbooks are in USD. The EUR currency code is just a default "aesthetics" option, that you can change at your convenience to reflect your true consumption agreement currency - you can then save the workbook to persist your option. It does not change the costs/savings values - only column headers and text referring to the currency.

**Comment by ashrafcitius** [comment]
@helderpinto Just one last question, may i know how is the cost calulation, like for the below screenshot is it based on month or year, or is there any calculation you have metioned in the script?  

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/139328727/ae606bcc-3e91-4e62-b545-cf3523758285)

**Comment by helderpinto** [comment]
@ashrafcitius, generally speaking, all the costs/savings calculations presented in the Recommendations workbook have a monthly base. This is always true for the "Custom" origin recommendations. For the "Advisor" origin ones, AOE uses the `annualSavingsAmount` property coming from the Advisor API, and divides the amount by 12, in order to keep all values consistently on a monthly basis.
