### ISSUE TITLE
Policy Compliance query state failed

### ISSUE THREAD

**Issue by ashrafcitius** [helderpinto/AzureOptimizationEngine#94]
@helderpinto For Policy Compliance the query state is showing as failed and below is the error i am getting on it

This query could not run because some parameters are not set.
Please set: Initiative, Definition, Assignment, Compliance State.
=====================================
Also for Outliers/growing costs conditions below is the error that i am getting.

This query could not run because some parameters are not set.
Please set: SelectedPerspective, SelectedPerspectiveId
==========================================

Also for benefits simulation below is the error that i am getting

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/139328727/9d8c370c-49ec-481a-99cd-beb331da0d6f)

**Comment by helderpinto** [comment]
**Policy Compliance**: please, check the output/errors of the latest job of the `Export-PolicyComplianceToBlobStorage` runbook. One possible reason is a high number of Policy States to export, which causes memory issues in the Automation sandbox.

**Costs Growing**: there is a note in the Workbook stating that "_If the first tile below ("Top Growing/Outliers") shows results, **select each line** to analyze the details of the costs growth over time for the specific line item._". If you have results in the first tile, just click one of the line items and the remaining tiles will load.

**Benefits Simulation**: there is a note in the Workbook stating that "_If below tabs are reporting query errors, you must set up Pricesheet exports. See more details [here](https://github.com/helderpinto/AzureOptimizationEngine#enabling-the-reservations-and-benefits-usage-workbooks)._" Please ensure you have configured the pre-requisites. If you believe you did, please check the output/errors of the latest job of the `Export-PriceSheetToBlobStorage` runbook.

**Comment by ashrafcitius** [comment]
You are right, for  Policy Compliance  the output/errors of the latest job of the Export-PolicyComplianceToBlobStorage runbook. One possible reason is a high number of Policy States to export, which causes memory issues in the Automation sandbox.

I am configuring a hybrid worker for this which will remediate this problem.

Whereas for **Costs Growing** what can be done for this.

**Comment by helderpinto** [comment]
@ashrafcitius, if you deployed recently AOE, then you may not have enough consumption history in Log Analytics to show growing costs. Otherwise, you may have a stable consumption track and the algorithm isn't able to find any growth trend.

**Comment by ashrafcitius** [comment]
@helderpinto Is there anything we can do to resolve below error for Export-AzMonitorMetricsToBlobStorage:
The runbook job failed due to sandbox using all its allocated network sockets. Azure sandboxes are limited to 1000 concurrent network sockets.The job was attempted 3 times before it was suspended.

**Comment by ashrafcitius** [comment]
@helderpinto I also wanted to know, how we can resolve below error:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/139328727/02d59830-dc66-4f26-ae19-a7d2ccb34eca)

**Comment by ashrafcitius** [comment]
@helderpinto Now i see that there is an error popping up for Identities and Roles workbook regarding query:

![image](https://github.com/helderpinto/AzureOptimizationEngine/assets/139328727/cdef5671-f696-4c51-9683-97fca6043604)

Below is the query from the log analytics, i have not changed anything:
let expiryInterval = 30d;
let AADObjectsTable = materialize(AzureOptimizationAADObjectsV1_CL
    | where TimeGenerated > ago(1d)
    | where TenantGuid_g in ());
let RBACAssignmentsTable = materialize(AzureOptimizationRBACAssignmentsV1_CL
    | where TimeGenerated > ago(1d)
    | where TenantGuid_g in ());
let AppsAndKeys = materialize (AADObjectsTable
    | where ObjectType_s in ('Application', 'ServicePrincipal')
    | where ObjectSubType_s != 'ManagedIdentity'
    | where Keys_s startswith '['
    | extend Keys = parse_json(Keys_s)
    | project-away Keys_s
    | mv-expand Keys
    | evaluate bag_unpack(Keys)
    | union ( 
        AADObjectsTable
        | where ObjectType_s in ('Application', 'ServicePrincipal')
        | where ObjectSubType_s != 'ManagedIdentity'
        | where isnotempty(Keys_s) and Keys_s !startswith '['
        | extend Keys = parse_json(Keys_s)
        | project-away Keys_s
        | evaluate bag_unpack(Keys)
        )
    );
let ExpirationInRisk = AppsAndKeys
    | where EndDate < now() + expiryInterval and EndDate > now()
    | project ApplicationId_g, KeyId, RiskDate = EndDate;
let NotInRisk = AppsAndKeys
    | where EndDate > now() + expiryInterval
    | project ApplicationId_g, KeyId, ComfortDate = EndDate;
let ApplicationsInRisk = ExpirationInRisk
    | join kind=leftouter (NotInRisk) on ApplicationId_g
    | where isempty(ComfortDate)
    | summarize ExpiresOn = max(RiskDate) by ApplicationId_g;
let ServicePrincipals = materialize(AADObjectsTable
    | where isnotempty(ObjectId_g)
    | where ObjectType_s == 'ServicePrincipal'
    | project SPNId = ObjectId_g, ApplicationId_g, PrincipalNames_s, DisplayName_s);
let GroupMemberships = AADObjectsTable
    | where ObjectType_s == 'Group' and SecurityEnabled_s == 'True'
    | where PrincipalNames_s startswith '['
    | extend GroupMember = parse_json(PrincipalNames_s)
    | project-away PrincipalNames_s
    | mv-expand GroupMember
    | union (
        AADObjectsTable
        | where ObjectType_s == 'Group' and SecurityEnabled_s == 'True'
        | where isnotempty(PrincipalNames_s) and PrincipalNames_s !startswith '['
        | extend GroupMember = parse_json(PrincipalNames_s)
        | project-away PrincipalNames_s
        )
    | project
        GroupId = ObjectId_g,
        GroupName = DisplayName_s,
        GroupMember = tostring(GroupMember),
        TenantGuid_g,
        Cloud_s;
let DirectAssignments = RBACAssignmentsTable
    | join kind=inner (
        ServicePrincipals
        )
        on $left.PrincipalId_g == $right.SPNId
    | project
        ApplicationId_g,
        PrincipalNames_s,
        DisplayName_s,
        RoleDefinition_s,
        Scope_s,
        Assignment = 'Direct',
        Model_s,
        TenantGuid_g;
let GroupAssignments = RBACAssignmentsTable
    | join kind=inner (
        GroupMemberships
        | join kind=inner ( 
            ServicePrincipals
            )
            on $left.GroupMember == $right.SPNId
        )
        on $left.PrincipalId_g == $right.GroupId
    | project
        ApplicationId_g,
        PrincipalNames_s,
        DisplayName_s,
        RoleDefinition_s,
        Scope_s,
        Assignment = strcat('Group>', GroupName),
        Model_s,
        TenantGuid_g;
AppsAndKeys
| join kind=inner (ApplicationsInRisk) on ApplicationId_g
| summarize ExpiresOn = max(EndDate) by ApplicationId_g, DisplayName_s, Cloud_s, KeyType, TenantGuid_g
| join kind=leftouter (
    GroupAssignments
    | union DirectAssignments
    )
    on ApplicationId_g
| summarize countif(isnotempty(RoleDefinition_s)) by DisplayName_s, ExpiresOn, KeyType, TenantGuid_g, ApplicationId_g
| order by countif_ desc, ExpiresOn asc

**Comment by helderpinto** [comment]
> @helderpinto Is there anything we can do to resolve below error for Export-AzMonitorMetricsToBlobStorage: The runbook job failed due to sandbox using all its allocated network sockets. Azure sandboxes are limited to 1000 concurrent network sockets.The job was attempted 3 times before it was suspended.

If this happens too often, then you should consider scheduling these jobs in a Hybrid Worker, due to the limitations of the Azure sandboxes.

**Comment by helderpinto** [comment]
> @helderpinto I also wanted to know, how we can resolve below error for Reservation Potential:
> 
> ![image](https://user-images.githubusercontent.com/139328727/267332690-02d59830-dc66-4f26-ae19-a7d2ccb34eca.png)

As stated by the header of the tile you pointed out, you just have to click on a line on the table shown in the left tile to load the other tiles charts. This UX is consistent with the Costs Growing UX, for example.

**Comment by helderpinto** [comment]
> @helderpinto Now i see that there is an error popping up for Identities and Roles workbook regarding query:
> 
> ![image](https://user-images.githubusercontent.com/139328727/267374323-cdef5671-f696-4c51-9683-97fca6043604.png)
> 
> Below is the query from the log analytics, i have not changed anything: let expiryInterval = 30d; let AADObjectsTable = materialize(AzureOptimizationAADObjectsV1_CL | where TimeGenerated > ago(1d) | where TenantGuid_g in ()); let RBACAssignmentsTable = materialize(AzureOptimizationRBACAssignmentsV1_CL | where TimeGenerated > ago(1d) | where TenantGuid_g in ()); let AppsAndKeys = materialize (AADObjectsTable | where ObjectType_s in ('Application', 'ServicePrincipal') | where ObjectSubType_s != 'ManagedIdentity' | where Keys_s startswith '[' | extend Keys = parse_json(Keys_s) | project-away Keys_s | mv-expand Keys | evaluate bag_unpack(Keys) | union ( AADObjectsTable | where ObjectType_s in ('Application', 'ServicePrincipal') | where ObjectSubType_s != 'ManagedIdentity' | where isnotempty(Keys_s) and Keys_s !startswith '[' | extend Keys = parse_json(Keys_s) | project-away Keys_s | evaluate bag_unpack(Keys) ) ); let ExpirationInRisk = AppsAndKeys | where EndDate < now() + expiryInterval and EndDate > now() | project ApplicationId_g, KeyId, RiskDate = EndDate; let NotInRisk = AppsAndKeys | where EndDate > now() + expiryInterval | project ApplicationId_g, KeyId, ComfortDate = EndDate; let ApplicationsInRisk = ExpirationInRisk | join kind=leftouter (NotInRisk) on ApplicationId_g | where isempty(ComfortDate) | summarize ExpiresOn = max(RiskDate) by ApplicationId_g; let ServicePrincipals = materialize(AADObjectsTable | where isnotempty(ObjectId_g) | where ObjectType_s == 'ServicePrincipal' | project SPNId = ObjectId_g, ApplicationId_g, PrincipalNames_s, DisplayName_s); let GroupMemberships = AADObjectsTable | where ObjectType_s == 'Group' and SecurityEnabled_s == 'True' | where PrincipalNames_s startswith '[' | extend GroupMember = parse_json(PrincipalNames_s) | project-away PrincipalNames_s | mv-expand GroupMember | union ( AADObjectsTable | where ObjectType_s == 'Group' and SecurityEnabled_s == 'True' | where isnotempty(PrincipalNames_s) and PrincipalNames_s !startswith '[' | extend GroupMember = parse_json(PrincipalNames_s) | project-away PrincipalNames_s ) | project GroupId = ObjectId_g, GroupName = DisplayName_s, GroupMember = tostring(GroupMember), TenantGuid_g, Cloud_s; let DirectAssignments = RBACAssignmentsTable | join kind=inner ( ServicePrincipals ) on $left.PrincipalId_g == $right.SPNId | project ApplicationId_g, PrincipalNames_s, DisplayName_s, RoleDefinition_s, Scope_s, Assignment = 'Direct', Model_s, TenantGuid_g; let GroupAssignments = RBACAssignmentsTable | join kind=inner ( GroupMemberships | join kind=inner ( ServicePrincipals ) on $left.GroupMember == $right.SPNId ) on $left.PrincipalId_g == $right.GroupId | project ApplicationId_g, PrincipalNames_s, DisplayName_s, RoleDefinition_s, Scope_s, Assignment = strcat('Group>', GroupName), Model_s, TenantGuid_g; AppsAndKeys | join kind=inner (ApplicationsInRisk) on ApplicationId_g | summarize ExpiresOn = max(EndDate) by ApplicationId_g, DisplayName_s, Cloud_s, KeyType, TenantGuid_g | join kind=leftouter ( GroupAssignments | union DirectAssignments ) on ApplicationId_g | summarize countif(isnotempty(RoleDefinition_s)) by DisplayName_s, ExpiresOn, KeyType, TenantGuid_g, ApplicationId_g | order by countif_ desc, ExpiresOn asc

This is typically a symptom of failures of the `Export-AADObjectsToBlobStorage` runbook. The most common issues are lack of permissions in Azure AD, lack of resources in the Azure sandbox (needs a Hybrid Worker) or a too large Azure AD (more than 50K objects).

**Comment by ashrafcitius** [comment]
@helderpinto Are you aware about below error for Export-AzMonitorMetricsToBlobStorage Runbook:

Get-AzMetric : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound' at Microsoft.Azure.Management.Monitor.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.<ListAsync>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal() at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null At line:168 char:25 + ... ricValues = Get-AzMetric -ResourceId $resource.id -MetricName $metric ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : CloseError: (:) [Get-AzMetric], PSInvalidOperationException + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand

**Comment by helderpinto** [comment]
@ashrafcitius, this error/warning typically occurs when one of the resources that was selected to extract metrics from ceased to exist when the Metrics API was called. This happens frequently with Databricks VMs, which are short-lived. I guess the job still completed successfully, despite the error message, right?

**Comment by ashrafcitius** [comment]
@helderpinto Yes the job did got completed.

**Comment by helderpinto** [comment]
This issue is now being closed, as all the questions have been answered. Thanks for your contributions.
