### ISSUE TITLE
Can only see count, how to check the details

### ISSUE THREAD

**Issue by ashrafcitius** [helderpinto/AzureOptimizationEngine#95]
@helderpinto Just wanted to know, while checking out the report, we can only see resource count for unattached NIC, Unallocated Public IP, Load balancer without any backend pool etc, may i know how should i check those resource details, as i can only see count.

**Comment by helderpinto** [comment]
I guess you are referring to the Resources Inventory workbook. Yes, this workbook only shows counts. For details about these orphaned resources, you should check the Recommendations Workbook, which has Cost and Operational Excellence recommendations for those.
