### ISSUE TITLE
Do you have plan to adapt to deploying DCR Rules for Data collections?

### ISSUE THREAD

**Issue by rasselmaliyekkal** [helderpinto/AzureOptimizationEngine#98]
If we create DCR Rules with perf counters mentioned in your article, will it work the same way expected?

**Comment by helderpinto** [comment]
Thanks for raising this issue, @rasselmaliyekkal. Your understanding is correct. A DCR collecting Perf counters will work the same way as expected by the right-size augmented recommendations. Support for Perf DCRs in the AOE toolset is in the roadmap and will be available soon.
