### ISSUE TITLE
Any option for checking the VM in idle state for more than a specific time period

### ISSUE THREAD

**Issue by ashrafcitius** [helderpinto/AzureOptimizationEngine#99]
@helderpinto Can this tool show us, number of vm's and its details which are in idle state for more than a specific time period like 30/60/90 days? It would be really helpful.

**Comment by helderpinto** [comment]
Hi, @ashrafcitius.  Can you clarify what you mean by "idle state"? Is it a deallocated VM? Is it a VM running with very low CPU usage?

**Comment by ashrafcitius** [comment]
@helderpinto I mean the VM which are having low CPU usage for a longer period of time like 30/60/90 days

**Comment by helderpinto** [comment]
@ashrafcitius , this isn't controlled by AOE. This is an Azure Advisor setting, you can change in the Advisor Configuration. More details [here](https://learn.microsoft.com/en-us/azure/advisor/advisor-get-started#configure-recommendations).
